// window.addEventListener('scroll', function(event) {
//     var depth, i, layer, layers, len, movement, topDistance, translate3d;
//     topDistance = this.pageYOffset;
//     layers = document.querySelectorAll("[data-type='parallax']");
//     for (i = 0, len = layers.length; i < len; i++) {
//       layer = layers[i];
//       depth = layer.getAttribute('data-depth');
//       movement = -(topDistance * depth);
//       translate3d = 'translate3d(0, ' + movement + 'px, 0)';
//       layer.style['-webkit-transform'] = translate3d;
//       layer.style['-moz-transform'] = translate3d;
//       layer.style['-ms-transform'] = translate3d;
//       layer.style['-o-transform'] = translate3d;
//       layer.style.transform = translate3d;
//     }
// });

function castParallax() {

	var opThresh = 350;
	var opFactor = 750;

	window.addEventListener("scroll", function(event){

		var top = this.pageYOffset;

		var layers = document.getElementsByClassName("parallax");
		var layer, speed, yPos;
		for (var i = 0; i < layers.length; i++) {
			layer = layers[i];
			speed = layer.getAttribute('data-speed');
			var yPos = -(top * speed / 100);
			layer.setAttribute('style', 'transform: translate3d(0px, ' + yPos + 'px, 0px)');

		}
	});
}

document.body.onload = castParallax();
  
  // ---
  // generated by coffee-script 1.9.2

$(document).ready(function(){
  AOS.init();
  
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

  $(document).on('click', 'a[href^="#"]', function (event) {
		$('html, body').animate({
			scrollTop: $($.attr(this, 'href')).offset().top
		}, 600);
  });
  
  // $(document).octoberLeaves({
  //   leafStyles: 3,      // Number of leaf styles in the sprite (leaves.png)
  //   speedC: 2,  // Speed of leaves
  //   rotation: 1,// Define rotation of leaves
  //   rotationTrue: 1,    // Whether leaves rotate (1) or not (0)
  //   numberOfLeaves: 15, // Number of leaves
  //   size: 40,   // General size of leaves, final size is calculated randomly (with this number as general parameter)
  //   cycleSpeed: 30      // <a href="https://www.jqueryscript.net/animation/">Animation</a> speed (Inverse frames per second) (10-100)
  // })
})